### ISSUE TITLE
Include vlan id inside the ansible yaml config

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#171]
Dell uses:
```
  Vlan 3607:
    description: urn:ogf:network:service+858b5c37-5af7-4e8a-9dc7-747abb7e0928:vt+l2-policy::Connection_1
    ipv6_address: {'fc00:0:0:0:0:0:0:16/124': present}
    name: Vlan 3607
    state: present
    tagged_members: {hundredGigE 1/7: present}
    vrf: lhcone
```
Arista uses:
```
  Vlan1798:
    description: urn:ogf:network:service+8791cc78-e68c-4d52-9b7c-3c6f3e9d2795:resource+links::Connection_1
    ipv4_address: {10.251.85.2/24: present}
    ipv6_address: {'fc00:0:0:0:0:0:0:16/124': present}
    name: Vlan1798
    state: present
    tagged_members:
      Ethernet31/1: present
      Ethernet30/1: present
```
And the issue is "VlanXXXX" vs "Vlan XXXX". We should include vlan id inside interface config parameters.
