### ISSUE TITLE
Service launch (docker container/kubernetes container)

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#212]
Agents should have a new service (ServiceLauncher) - which can launch one or more docker/kubernetes services on the agent. E.g. 
```
virtualization:
  subsystem: docker | kubernetes
  max_runtime: 3600 # 0 means unlimited
  max_idle_time: 24*7*3600 # 0 means unlimited
  containers:
    <container_name_version>:
      max_runtime: 240000
      max_idle_time: 24*7*3600
      container_config:
        docker_config_param_1: docker_config_val_1
        ....
```
With this - FE could list all possible launch containers, e.g. Jupiter notebook - which can help for debug purposes. (Or, in the future, start other services, like xrootd, fdt, net tester, etc)
