### ISSUE TITLE
Podman, Docker, Docker-CE logging option

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#261]
```
Server:
 Plugins:
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
```
or
```
host:
  arch: ppc64le
  logDriver: k8s-file
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
```
SiteRM Startup (Docker scripts/Podman Scripts) should check available log options and use it (default we use json-file)
