### ISSUE TITLE
FE k8s does not map https port correctly

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#34]
@juztas By installers/fe-docker/sitefe-k8s.yaml, host port 8443 should have been mapped to FE pod port 443.

However, this did not work. I can access port 443 from inside pod but not 8443 from outside. Some config is incorrect in the sitefe-k8s.yaml.

**Comment by juztas** [comment]
Where you run your k8s?

**Comment by xi-yang** [comment]
I patched my deployment with `NodePort` and `externalIPs` statement. But I also realized these are options we can put in the deployment command. So no issues here. 
```
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "8443"
    port: 8443
    targetPort: 443
  externalIPs:
    - 206.196.180.131
  selector:
    io.kompose.service: sitefe
```

@juztas You may review and then close this.
