### ISSUE TITLE
Config parser change

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#346]
Right now, we have to specify ports like this:
```
  ports:
    - "Ethernet1/49"
    - "Ethernet1/51"
    - "Ethernet1/52"
  port_Ethernet1-49_capacity: 100000
  port_Ethernet1-49_desttype: switch
  port_Ethernet1-49_isAlias: "isAliasLink"
  port_Ethernet1-49_wanlink: "Ethernet1/49"
```
Problem is that it is easy to make a mistake and not change " " to "_" or "/" to "-". We need to migrate config definition to something like:
```
  ports:
    "Ethernet1/49":
        "capacity": 100000
        "desttype": switch
        "isAlias": "isAlias"
        "wanlink": true
    "Ethernet1/51": {}
    "Ethernet1/52": {}
```
