### ISSUE TITLE
Ping/Traceroute from Switches/Routers + from private NS

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#413]
As we discussed in the meeting, a new feature would also be nice to have in debuggers:

- [x] Ping/Traceroute from Switches/Routers;
- [ ] Ping/Traceroute from Private Network Namespaces (For Sites using Multus and privatens)
- [x] Ping/Traceroute from a specific IP if not using Multus, but uses macvlans.

**Comment by juztas** [comment]
```
dell os 9:
ping vrf lhcone 2001:48d0:3001:111:: count 10 timeout 5
traceroute vrf lhcone 2001:48d0:3001:111::400
dell os 10:
ping6 vrf Vrf_sense01 fc00::3600 -i 1 -c 5
traceroute  vrf Vrf_sense01 fc00::3600

aristaeos:
ping vrf default ip 198.32.43.1 timeout 5 repeat 10
ping vrf default ipv6 2001:48d0:3001:111::400 timeout 5 repeat 5

traceroute vrf default ip 198.32.43.1
traceroute vrf default ipv6 fc00:3600::

cisco nexus9:
ping 8.8.8.8 vrf default timeout 5 interval 5 count 5
ping6 fc00::3600 vrf default timeout 5 interval 5 count 5

traceroute 8.8.8.8 vrf default
traceroute6 fc00::3600 vrf default

sonic:
traceroute6 fc00::3600
traceroute 8.8.8.8
ping fc00::3600 -i 1 -c 5
ping 8.8.8.8 -i 1 -c 5
```

**Comment by juztas** [comment]
Template to be used for all is the following (as first start):
```
ping:
  type: ipv6
  vrf: lhcone
  ipv6_address: 2001:48d0:3001:111::
  ipv4_address: 8.8.8.8
  count: 10
  timeout: 5

ping:
  type: ipv4
  vrf: lhcone
  ipv4_address: 8.8.8.8
  count: 10
  timeout: 5

traceroute:
  type: ipv6
  vrf: lhcone
  ipv6_address: 2001:48d0:3001:111::

traceroute:
  type: ipv4
  vrf: lhcone
  ipv4_address: 8.8.8.8
```
