### ISSUE TITLE
1.4.3 Release documentation tracker

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#447]
Config changes for all switch ports (Merged here: https://github.com/sdn-sense/siterm/issues/346)
```
Right now, we have to specify ports like this:

  ports:
    - "Ethernet1/49"
    - "Ethernet1/51"
    - "Ethernet1/52"
  port_Ethernet1-49_capacity: 100000
  port_Ethernet1-49_desttype: switch
  port_Ethernet1-49_isAlias: "isAliasLink"
  port_Ethernet1-49_wanlink: "Ethernet1/49"
Problem is that it is easy to make a mistake and not change " " to "_" or "/" to "-". We need to migrate config definition to something like:

  ports:
    "Ethernet1/49":
        "capacity": 100000
        "desttype": switch
        "isAlias": "isAlias"
        "wanlink": true
    "Ethernet1/51": {}
    "Ethernet1/52": {}
```
bwParams (https://github.com/sdn-sense/siterm/issues/432)
```
under host interface:
bwParams:
  type: guaranteedCapped
  priority:
  reservableCapacity: reservable capacity for siterm on that interface (Default 100%)
  minReservableCapacity
  maximumCapacity
  granularity
under host agent:
  reservableCapacity: reservable capacity for all siterm interfaces (will be used for all configured ports if port does not mention explicitly. Default 100%)


under switch port:
  reservableCapacity: Either % or speed in mbps; Default 100%
under switch:
  reservableCapacity: Either % or speed in mbps - will be used for all ports if port does not mention explicitly. Default 100%
```
