### ISSUE TITLE
Deployment of FEs add nodeAffinity

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#561]
For all Caltech deployments, ignore sdn-dtn-2-11; similar for prod cluster, ignore k8s-pb10, which seems to have issues.
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - sdn-dtn-2-11.ultralight.org
```
