### ISSUE TITLE
helm agent security context control via values.yaml

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#570]
```
       securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
```
