### ISSUE TITLE
Helm for FE improvements, fixes

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#605]
- [x] Automate Issuer for FE (it has it for agents)
- [x] Not use defaults from configuration [1]. Same happens for nodeSelector and affinity;
- [x] affinity - need 2 more spaces;
- [x] Find a way to add ssh key automatically

[1]
```
It uses the default from yaml:
# Ingess for Frontend. Ingress can also issue certificate, e.g. from letsencrypt.
# If you prefer to use cert-manager, set certmanager to true and configure certmanager_params.
# If you prefer to use files, set hostcert and hostkey to true and point to pem files.
ingress:
  enabled: true
  host: <REPLACE_ME_TO_FQDN>
  annotations:
    kubernetes.io/ingress.class: haproxy
    kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
```
