### ISSUE TITLE
Increase Liveness/Readiness probe timeout

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#797]
Sometimes SiteRM can be overloaded and liveness, readiness probe timeouts. Currently timeout is set to 1 second. We should increase this to 30 seconds and wait for 5 failures before really restarting
```
        readinessProbe:
          exec:
            command:
            - siterm-readiness
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        livenessProbe:
          exec:
            command:
            - siterm-liveness
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
```
