### ISSUE TITLE
Fake Port requires vlans to be in physical port

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#871]
Working config:
```
junos_s0:
  vlan_range:
    - 3901-3920
    - 3100-3109
  ports:
    "et-0/0/32": {}
    "ae2": {}
    "ae4":
      vlan_range:
        - 3100-3109
        - 3912-3920  # THIS IS ISSUE 
    "sense-mghpcc":
      realportname: "ae4" # This forces to check that ae4 has also requested vlan
      vlan_range:
        - 3912-3920
```
While it should be:
```
junos_s0:
  vlan_range:
    - 3901-3920
    - 3100-3109
  ports:
    "et-0/0/32": {}
    "ae2": {}
    "ae4":
      vlan_range:
        - 3100-3109
    "sense-mghpcc":
      realportname: "ae4" # This should not force check ae4 that it has vlan_range also
      vlan_range:
        - 3912-3920
```
It will accept and validate that the delta is correct, but once there is an activation, it will fail, because the second config has no 3914 in ae4. And the physical interface is ae4. 
Solution is if there is a fake port (and it has realportname in it) it should only check fake port vlans, not physical port
