### ISSUE TITLE
Minimize configuration parameters

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#9]
Now there are many config parameters which are copy paste or simple split from one or another, like:
```
  port1_1capacity: 100
  port1_1destport: cern-1
  port1_1desttype: switch
  port1_1hostname: production7
  port1_1isAlias: "urn:ogf:network:netherlight.net:2013:production7:cern-1"
  port1_1vlan_range: 3985-3989
  port1_2capacity: 100
  port1_2destport: enP48p1s0f1
  port1_2desttype: server
  port1_2hostname: surfnet-dtn
  port1_2vlan_range: 3985-3989
  port1_2isAlias: "urn:ogf:network:surfnet-dtn.cern.ch:2013:s0:1_2:surfnet-dtn:enP48p1s0f1"
  ports:
    - "1_1"
    - "1_2"
```
It should be enought to specify capacity and isAlias for remote. For local servers - Servers itself report the port, switch and interface.
